DROP TABLE IF EXISTS "endpointhit" CASCADE;

CREATE TABLE IF NOT EXISTS endpointhit (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app      varchar(255)                            NOT NULL,
    uri      varchar(512)                            NOT NULL,
    ip       varchar(127)                             NOT NULL,
    datetime timestamp                               NOT NULL,
    CONSTRAINT pk_hit PRIMARY KEY (id)
);